### ISSUE TITLE
Binary Search Algorithm

### ISSUE THREAD

**Issue by abhishekbhonde** [heysaiyad/Hacktoberfest2023-DSA#115]
Hey can you please assign this issue to me?

**Comment by Navaneeth210805** [comment]
@heysaiyad can you assign me with this issue

**Comment by GitPratyush** [comment]
I would like to work on this issue.

**Comment by abhayanand08** [comment]
@heysaiyad can you please assign me with this issue. I will add a great solution for this.

**Comment by Gyanshu-Kumar** [comment]
I have Batter and Easy to Understand Approach.
Can you please assign this issue to me

**Comment by ADNAAN18** [comment]
Hello,
Please assign this issue to me. I can contribute to the Binary Search Algorithm issue in a clear and concise way along with an explanation. I will also add code in different programming languages for better understanding.

Regards,
Adnaan.

**Comment by AbhineshJha** [comment]
hey ! i am interested in this issue , can i give it a try ?
can u assign me ??

**Comment by Satyam9119** [comment]
Hello @heysaiyad , I already worked on that problem please assign it to me .

**Comment by TheHackracer7** [comment]
@heysaiyad, sir plz assign this issue
