### ISSUE TITLE
02. Bit Magic - Add Binary

### ISSUE THREAD

**Issue by DhananjayGoyalGL** [heysaiyad/Hacktoberfest2023-DSA#120]
Want to add easy-level questions related to bit manipulation. Please assign.

**Comment by bhaveshgarg2000** [comment]
@DhananjayGoyalGL Please assign this issue to me

**Comment by DhananjayGoyalGL** [comment]
raised PR for it.. @heysaiyad

**Comment by Tejoooo** [comment]
heyy can u assign me this issue I m interested in this
