### ISSUE TITLE
I want to add the "kth smallest element" program in an array 

### ISSUE THREAD

**Issue by devrihan** [heysaiyad/Hacktoberfest2023-DSA#276]
Finding the kth largest element in an array in Cpp

**Comment by Saurabhchaudhary9799** [comment]
I want to work on this issue , please assign this to me .

**Comment by saku1331** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by iamakashrout** [comment]
I wish to contribute to this. Please assign this to me
